### ISSUE TITLE
Update the penalty addition

### ISSUE THREAD

**Issue by Aurelien-Valeille** [neokama/OpenApneeLyon#3]
https://github.com/neokama/OpenApneeLyon/blob/3b4f952ebbfa73feba89c97f81690af826fdbfeb/src/main/bddResult.go#L687-L733

**Comment by neokama** [comment]
Translated for rules of 2019 : 

850 :
if PRl > PA +40s then PRt = PRl + [PRl-(PA +40 sec)] x 3 sec
if PRl < PA-20s then then PRt  =(PA –20 secondes).

PRt max :
if H : PRl > 10min then PRt = 10min
if F : PRl > 12min then PRt = 12min

spd:
if PRl > PA +20s then PRt = PRt + [PRl-(PA +20 sec)] x 3 sec
if PRl < PA-10s then then PRt  =(PA –10 secondes).
